### ISSUE TITLE
Unicorn calculator: Unicorn Selection upgrade not tracked

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#1]
The base production of unicorns is inaccurate again after I bought a workshop upgrade called "Unicorn Selection" that adds a separate +25% modifier to unicorn production. That one will have to be tracked along with the other stuff so the calculation can be accurate.

![image](https://user-images.githubusercontent.com/14056473/61918679-867c8f80-af52-11e9-8b35-38ba409f71cf.png)

**Comment by VariableVixen** [comment]
I really need to grovel the game's codebase and find a way to get the effective unicorns per second that it shows the user without having to calculate every effect myself... I think this is the fourth or fifth issue stemming from a modifier not being accounted for.

**Comment by Quizer85** [comment]
The modifier that needs to be added is called `unicornsGlobalRatio`, but I couldn't figure out the proper syntax to add it in. I spent about an hour on it and gave up, before I did the other one. I was pretty close, but I couldn't figure out the proper commands to use because nothing else in the script depends on a workshop upgrade.

**Comment by Quizer85** [comment]
This should not be too tricky, honestly. All you have to do is figure out what it should say instead of, for example, `game.religion.getZU('skyPalace').effects.unicornsRatioReligion`, since the modifier we need is based on a workshop upgrade.

The relevant bit is in line #389: `return baseUps * bldEffect * faithEffect * paragonRatio;`
We need to define a new modifier, say, `upgEffect`, and do something similar to `faithEffect` in line #383-385. I just couldn't figure out the proper syntax, but you probably can since you added some stuff to this calc already.

**Comment by VariableVixen** [comment]
Workshop upgrades are in the `game.workshop.upgrades` array; it looks like only one upgrade - Unicorn Selection - has a `unicornsGlobalRatio` effect, but since I'd need to loop to find it I'll just grab any upgrades that have that... I think it's time to set up some caches of game data. Particularly if I'm also going to overhaul the autocrafting loop.
