### ISSUE TITLE
Redesign script settings UI to separate out different sections

### ISSUE THREAD

**Issue by VariableVixen** [PrincessRTFM/AutoKittens#13]
As noted in #10, the script's settings panel is getting too full, and with more settings planned it really needs to be split up. Current plan is to have one "directory" panel in place of the current one with buttons to open specific panels for things like autohunting options, autocrafting options, autotrading options, etc. You'd click the same thing you do now, then you'd hit the button for whatever you're looking for and _then_ you'd have the options. Clicking the close link in the corner will close it, clicking the settings link will close it and re-open the directory, and there'll be a "back" link near the close one that returns you to the directory as well.

**Comment by Quizer85** [comment]
I hope nesting everything one level (one click) deeper isn't going to be too annoying. But with the master switches, it'll probably be fine, since you won't need to go into the menu for everything.

**Comment by VariableVixen** [comment]
Master switches can be on the top level, that'd be fine, I just think that the autocrafting details _alone_ are _already_ too long, and it's only going to get longer.

**Comment by Quizer85** [comment]
Yeah, agreed.

**Comment by VariableVixen** [comment]
How's this look for a [master UI](https://i.imgur.com/6aM0ab3.png)? I'll add the toggles soon, just trying to get the core overhaul done right now (you wouldn't believe the unexpected bugs I found while trying to do this...)

**Comment by Quizer85** [comment]
Seems fine, though please make it so the various categories remember their opened / closed state. I would like this overhaul to introduce as small a number of additional clicks needed as possible.

**Comment by VariableVixen** [comment]
They're different panels, not sections on the main one. There isn't really an opened/closed state. I don't want to put them all back into one panel either, because that would mean losing the optimisations to the redraw code. Still, I think one extra click is acceptable, right?

**Comment by Quizer85** [comment]
If you have to keep doing that one extra click every time you want to do something in the settings, that's really unfortunate. I guess it might still be faster than having to scroll a bunch? Will have to see once the whole thing is actually finished.

**Comment by VariableVixen** [comment]
It really doesn't take that long to click one more time. Anyway, update is live.

**Comment by Quizer85** [comment]
But you're not clicking one more time. You're clicking one more time *every time* you do *anything* with the script. UI designers really, really like to underestimate the persistent cost of changes like this, and as a general principle should ask themselves, "Is it absolutely unavoidable / worth the trade-off to hide these settings behind an extra layer of UI and making people jump through an additional hoop to access them?"

In this case, it's probably fine. At the moment it's a wash between that extra click and having to scroll a bunch, and I assume it'll pay dividends later on.

**Comment by VariableVixen** [comment]
It's not going to close the window until you tell it to, for one thing. And for another, it lets me finally optimise the UI redraw code, which was previously redrawing (and therefor re*calculating*) every single element and data point every time you wanted to open the panel. It was already inducing noticeable lag, and the more I put in there the worse it'll get. You also have to weigh the cost of one extra click each time you want to change a setting (which aren't going to change that often) against how busy the UI is getting. Considering that the crafting section will grow to at least 1.5x the size, possible more than double, the busy-ness and the redraw lag are too problematic.
