### ISSUE TITLE
Unicorn calc needs burnt paragon

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#15]
The unicorn calculator's unicorn production is off again for me. I believe it's due to burnt paragon not being accounted for. This would be pretty easy if not for the fact that the paragon bonus used by the game uses both paragon and burnt paragon, each with their separate diminishing returns, and that burnt paragon's bonus changes once you reach the Dark Future. Do you think you can have a look at this?

**Comment by VariableVixen** [comment]
I'll check the wiki page on burnt paragon, yeah. If the game itself can account for it, AK can too, it just might be annoying to deal with.

**Comment by VariableVixen** [comment]
The holdup on this one, which would otherwise be easy (just insert an additional calculation after [line 458](https://github.com/PrincessRTFM/AutoKittens/blob/master/AutoKittens.src.js#L458)) is that burnt paragon uses diminishing returns, and I need to find the exact code the game uses to calculate it on production effects or the calculator will be completely off. From the wiki, emphasis mine:

> Every point of burnt paragon will give: (as of 1.4.0.7)
> 
> - 1% global production bonus (limit of +100% and **diminishing returns at 75** before Dark Future, limit of +400% and **diminishing returns at 300** during Dark Future)

**Comment by Quizer85** [comment]
I'm pretty sure it uses the same rate of diminishing returns as regular paragon, so you should be able to re-use that `game.getHyperbolicEffect` function for burnt paragon. The only complication is that it has two different states (depending on whether the Dark Future is active) and that burnt paragon and regular paragon stack additively, not multiplicatively.

The way the diminishing returns work is that the first value given (+200% for regular paragon, +100% / +400% for burnt paragon) is the goal value that is impossible to reach, because it would require infinite paragon / burnt paragon. The second value is 75% of the goal value (+150% for paragon, +75% / +300% for burnt paragon), and this is where the diminishing returns start setting in.

http://bloodrizer.ru/games/kittens/wiki/index.php?page=Diminishing+Returns
Here' the wiki page on diminishing returns. If you can't get it to work by re-using the function it uses for paragon, you can find the exact formula there.

**Comment by VariableVixen** [comment]
All calculators except the mint profit and the AIpocalypse have been removed. They're too complex to easily maintain with the rest of the script.
