### ISSUE TITLE
Uncaught TypeError: can't redefine non-configurable property "resmap"

### ISSUE THREAD

**Issue by WrayOfSunshine** [PrincessRTFM/AutoKittens#17]
Uncaught TypeError: can't redefine non-configurable property "resmap"
    injectGlobalReadOnlyValues https://princessrtfm.github.io/AutoKittens/AutoKittens.js?nocache:2427
    performFinalInitialisation https://princessrtfm.github.io/AutoKittens/AutoKittens.js?nocache:2528
    setupAutoKittens https://princessrtfm.github.io/AutoKittens/AutoKittens.js?nocache:2543
    <anonymous> https://princessrtfm.github.io/AutoKittens/AutoKittens.js?nocache:2544
AutoKittens.js:2427:10

**Comment by VariableVixen** [comment]
Did you try to load the script twice? Did you have any other scripts loaded as well?

**Comment by WrayOfSunshine** [comment]
Must've done the former, as I can't reproduce today.

**Comment by VariableVixen** [comment]
If you used a bookmarklet, you might've accidentally double-clicked it. Maybe I can implement a check for whether it's already been loaded to avoid this... I just use a userscript to inject it myself so I've never had this issue.

**Comment by WrayOfSunshine** [comment]
> If you used a bookmarklet, you might've accidentally double-clicked it. Maybe I can implement a check for whether it's already been loaded to avoid this... I just use a userscript to inject it myself so I've never had this issue.

I tried to load it as a userscript but violentmonkey didn't like it for some reason :(

**Comment by VariableVixen** [comment]
I don't think there's anything I can do about that. Personally, I don't load it _as_ a userscript, I use a userscript to inject it into the page, so maybe that might work better for you?
