### ISSUE TITLE
Suggestion: Master switches on main game screen to toggle features

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#5]
It would be nice if there were little master switches on the main game screen, for quickly toggling whole groups of features on and off. Something that happens all the time is that I want to build something, but the resource I need is being held at 99% when I need 99.5% (for example).

So every time that happens, I have to go in the options menu, scroll down and find the right checkmark to untick, build my thing, then go back and turn it on again. This actually happens a lot. It would be easier if I could just briefly toggle all crafting straight from the main screen.

We could have little icons that reside in the top bar, between the game title and the discord link. If you think this is a worthwhile idea, I can probably whip up a couple little pixel art icons that you can click. One for general resource crafting, one for parchment-stuff crafting, one for trade, one for hunting, one for faith... Something like that. Lemme know if you want the icons and I'll see what I can do.

**Comment by VariableVixen** [comment]
I like this idea, but I'm not sure about the top bar. A lot of scripts use it, and I don't know how many more features this script will accumulate that need master toggles. As an alternative, what about putting something in [this area](https://i.imgur.com/9HNr7zG.png) instead, maybe? I could also try looking at the code that deals with the chat/log switching, since I don't think most people really use the chat. Maybe add (or even replace chat with?) a master switch panel?

**Comment by Quizer85** [comment]
Yeah, putting it there could also work. In that case it can just be clickable text buttons. I just thought icons would fit better in the top bar.

Ideally the switches would be on screen all the time, though, so you could get at them with a single click. If you have to click on a category-thingy first, that kind of defeats the point of this idea.

**Comment by VariableVixen** [comment]
I can see that, although I'd also say that _part_ of the point is to have an overall control for a whole category - "no autocrafting" or "no trading" or what have you - in an easy to access place, that doesn't require you to scroll through a long dialog until you find it. I'll see what I can put together for that area.

**Comment by VariableVixen** [comment]
Another question, actually: should these be saved in the settings, or should they only last until a page reload, defaulting to "enabled" to let whatever they control run?

**Comment by Quizer85** [comment]
Probably best to save them along with the other settings. I'm really mostly thinking of them as an alternate way to control what's already in the script settings (as well as grouping a few things together), so they should behave like the normal settings. I could see it becoming obnoxious if you have to click a bunch of stuff every time you load the script to get things back to how you prefer.

**Comment by VariableVixen** [comment]
Hm, true. Okay, new settings to go with the global toggles then.

**Comment by VariableVixen** [comment]
I can't find a good design for this, and honestly it's not really needed. The use case was turning off autocrafting, but the autocrafting panel has a toggle at the top to do that already.
